### DISCUSSION TITLE
Confused about toml file generation/writing

### DISCUSSION THREAD

**Discussion by Stein-N** [TheElectronWill/night-config#153] [Q&A]
I'm confused about why on Neo-/Forge categories in the toml file get writen with a blank line between/above them, but when i use it on Fabric they get "crunshed" together. Is there a setting for the CommentedConfig or the TomlWriter i can set to achive this?

Neo-/Forge:
```toml

["Crack Hammer Durability"]
	copper = 64
	gold = 96
	iron = 128
	steel = 160
	diamond = 256
	netherite = 384

["Chisel Durability"]
	copper = 10
	gold = 15
	iron = 30
	steel = 45
	diamond = 64
	netherite = 96
```

Fabric:
```toml
["Crack Hammer Durability"]
	copper = 64
	gold = 96
	iron = 128
	steel = 160
	diamond = 256
	netherite = 384
["Chisel Durability"]
	copper = 10
	gold = 15
	iron = 30
	steel = 45
	diamond = 64
	netherite = 96
```

For all Modloaders i use my simple API to Build and create the Config File.

My current approach, i guess, is not the best but for now i cant imagine a better way:

[Repo for the Config API](https://github.com/Stein-N/Simple-Config-API/tree/main/common/src/main/java/net/xstopho/simpleconfig)

[Writing every Config Entry to the Commented Config](https://github.com/Stein-N/Simple-Config-API/blob/main/common/src/main/java/net/xstopho/simpleconfig/config/SimpleModConfig.java#L47)

Method for writing the Values to the CommentedConfig wich is initialized as inMemory():
```java
    private void writeToConfig(ConfigEntry<?> entry) {
        for (Map.Entry<String, String> categoryComment : this.builder.getCategoryComments().entrySet()) {
            this.config.setComment(categoryComment.getKey(), categoryComment.getValue());
        }

        this.config.set(entry.path, entry.value);

        if (entry.configValue.getRangedComment() == null) this.config.setComment(entry.path, entry.configValue.getComment());
        else this.config.setComment(entry.path, entry.configValue.getRangedComment());
    }
```

Method for saving/generating the toml file:
```java
    private void writeValuesToTomlFile() {
        TomlWriter writer = new TomlWriter();
        writer.write(this.config, this.file, WritingMode.REPLACE);
    }
```

I tried to "modify" the TomlWriter, by adding the writer.setNewLine() like below, but then every value has a blank line above.
When i only add one \n the result is the same, that the categories get crunshed together.
```java
    private void writeValuesToTomlFile() {
        TomlWriter writer = new TomlWriter();
        writer.setNewline("\n\n");
        writer.write(this.config, this.file, WritingMode.REPLACE);
    }
```

After checking how the ModConfig from Forge handles the saving, i also tried like Forge to cast my CommentedConfig to the CommentedFileConfig to use the .save() method but this produces an Exception that a CommentedConfig cannot be cast to CommentedFileConfig
```java
    private void writeValuesToTomlFile() {
//        TomlWriter writer = new TomlWriter();
//        writer.write(this.config, this.file, WritingMode.REPLACE);
        ((CommentedFileConfig) this.config).save();
    }
```
