### ISSUE TITLE
Help tables

### ISSUE THREAD

**Issue by mani1232** [TheElectronWill/night-config#112]
Hello, can you suggest a way to get Map<String, Config> from FileConfig
![image](https://user-images.githubusercontent.com/70480001/179201578-531917b2-6548-43ac-accc-4b32665886fc.png)
Or is it only possible through TomlParser?

**Comment by TheElectronWill** [comment]
First remark: what you have here is the following structure:
```python
tickets = {}
custom-tickets = {
  text = "tickets"
}
custom-tickets1 = ...
```
Do you want nested tables instead? If so, here is the right toml syntax:
```toml
[tickets.custom-tickets]
text = "tickets"
[tickets.cutstom-tickets1]
# ...
```
Yes, you have to repeat the whole path. See the example on the [TOML website](https://toml.io/en/), with `servers.alpha`.

Now, to answer your question
> can you suggest a way to get Map<String, Config> from FileConfig

What are you trying to do?
A FileConfig is already a Map-like structure. You can call `get` to obtain the values in it, including sub (nested) configs :)

For instance, if you have this:
```toml
[tickets.sub1]
text = "tickets 1"
[tickets.sub2]
text = "tickets 2"
```
You can do:
```java
FileConfig config = FileConfig.of(file);
Config tickets = config.get("tickets");
Config sub1 = tickets.get("sub1");
String sub1Text = sub1.get("text"); // you can also do tickets.get("sub1.text")
```
