### ISSUE TITLE
How add and remove config sections

### ISSUE THREAD

**Issue by mani1232** [TheElectronWill/night-config#115]
For example, I have a structure like this (file format .toml)

```toml
[guild-name1]
    [username1]
        counter = ""
        other-data = ""
    [username1]
        counter = ""
        other-data = ""
[guild-name2]
    [username2]
        counter = ""
        other-data = ""
[guild-name44]
    [username1]
        counter = ""
        other-data = ""
```

How create [guild-name1] and [username1] in [guild-name1] and in [username1] sections

**Comment by mani1232** [comment]
(And how remove)

**Comment by TheElectronWill** [comment]
I've edited your post to mark the code as code, in markdown this is done with backticks (```):

```md
\`\`\`toml
toml here
\`\`\`
```

**Comment by mani1232** [comment]
Rename?🤗

**Comment by TheElectronWill** [comment]
Rename = Remove with old name + Set with new name :)

**Comment by mani1232** [comment]
i did so
![image](https://user-images.githubusercontent.com/70480001/190102734-b2faf52f-95d0-45b2-91a5-9c3f9a652fde.png)
I got it
```toml
[965722681238503524]
	guild-name = "Тестовый сервер"

	[965722681238503524.792689746156978207]
		personal-counter = 0
		username = "WorldMandia тест"

	[965722681238503524.486559882825302027]
		personal-counter = 0
		username = "mani123"
````
I need
```toml
[965722681238503524]
	guild-name = "Тестовый сервер"

	[792689746156978207]
		personal-counter = 0
		username = "WorldMandia тест"

	[486559882825302027]
		personal-counter = 0
		username = "mani123"
````

What have I done wrong?

**Comment by TheElectronWill** [comment]
You've done nothing wrong, the output is correct. In TOML, the sub-section `a.b` is always serialized as `[a.b]`, not `[b]`, because TOML doesn't care about the identation of your file.

This:
```toml
[a]
key = "value"
    [b]
    k2 = "v2"
```

Is actually the same as this:
```
[a]
key = "value"

[b] // b is NOT inside of a!
k2 = "v2"
```

But you want this:
```toml
[a]
key = "value"

[a.b]
k2 = "v2"
```
This is explained in the [TOML specification](https://toml.io/en/v1.0.0).
