### ISSUE TITLE
Hide toml subgroups

### ISSUE THREAD

**Issue by mani1232** [TheElectronWill/night-config#123]
![image](https://user-images.githubusercontent.com/70480001/195721977-fb1d2716-90f3-42a1-9787-29f213595a85.png)
Is there any way to hide or remove it?

**Comment by mani1232** [comment]
![image](https://user-images.githubusercontent.com/70480001/195720654-8bd4a045-276e-4928-8309-e026b4b18546.png)
Update image

**Comment by TheElectronWill** [comment]
It's possible, according to the toml spec.
In practice the TomlWriter lacks the ability to detect "useless" middle groups. So that's a nice frature enhancement request :)

**Comment by mani1232** [comment]
and add path.path.*
* is any strings

**Comment by TheElectronWill** [comment]
> and add path.path.*
> '*' is any strings

Do you mean that it would do the same as:
```java
Config cfg = config.get("path.path")
```

?

**Comment by albilu** [comment]
Any plan to solve this?

**Comment by TheElectronWill** [comment]
Yes! In the following weeks I hope to be able to get some free time to fix this.

Note that, IIRC, this still produces valid toml files.

**Comment by albilu** [comment]
No it doesnt. It brokes pyproject.toml for exemple.

**Comment by TheElectronWill** [comment]
> No it doesnt. It breakes pyproject.toml for exemple. 

That's a bug on their side, then.
On the [official TOML website](https://toml.io/en), the first example contains an empty intermediate level `servers`.

**Comment by albilu** [comment]
> > No it doesnt. It breakes pyproject.toml for exemple.
> 
> That could be a bug on their side, then. On the [official TOML website](https://toml.io/en), the first example contains an empty intermediate level `servers`.

Actually you are right. i tested again and somehow it is working and doesn't prevent the build. 
The thing is that its mess up the formatting a lot.

**Comment by TheElectronWill** [comment]
Thank you for the feedback!
Which formatter do you use?

**Comment by albilu** [comment]
No particular formatter. Here is example of update with night config.
**Before:**
```toml
# Copyright 2017-2020 Palantir Technologies, Inc.
# Copyright 2021- Python Language Server Contributors.

[build-system]
requires = ["setuptools>=61.2.0", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[project]
name = "python-lsp-server"
authors = [{name = "Python Language Server Contributors"}]
description = "Python Language Server for the Language Server Protocol"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.7"
dependencies = [
    "jedi>=0.17.2,<0.19.0",
    "python-lsp-jsonrpc>=1.0.0",
    "pluggy>=1.0.0",
    "docstring-to-markdown",
    "ujson>=3.0.0",
    "setuptools>=39.0.0",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/python-lsp/python-lsp-server"

[project.optional-dependencies]
all = [
    "autopep8>=1.6.0,<2.1.0",
    "flake8>=5.0.0,<7",
    "mccabe>=0.7.0,<0.8.0",
    "pycodestyle>=2.9.0,<2.11.0",
    "pydocstyle>=6.3.0,<6.4.0",
    "pyflakes>=2.5.0,<3.1.0",
    "pylint>=2.5.0,<3",
    "rope>1.2.0",
    "yapf>=0.33.0",
    "whatthepatch>=1.0.2,<2.0.0"
]
autopep8 = ["autopep8>=1.6.0,<2.1.0"]
flake8 = ["flake8>=5.0.0,<7"]
mccabe = ["mccabe>=0.7.0,<0.8.0"]
pycodestyle = ["pycodestyle>=2.9.0,<2.11.0"]
pydocstyle = ["pydocstyle>=6.3.0,<6.4.0"]
pyflakes = ["pyflakes>=2.5.0,<3.1.0"]
pylint = ["pylint>=2.5.0,<3"]
rope = ["rope>1.2.0"]
yapf = ["yapf>=0.33.0", "whatthepatch>=1.0.2,<2.0.0"]
websockets = ["websockets>=10.3"]
test = [
    "pylint>=2.5.0,<3",
    "pytest",
    "pytest-cov",
    "coverage",
    "numpy",
    "pandas",
    "matplotlib",
    "pyqt5",
    "flaky",
]

[project.entry-points.pylsp]
autopep8 = "pylsp.plugins.autopep8_format"
folding = "pylsp.plugins.folding"
flake8 = "pylsp.plugins.flake8_lint"
jedi_completion = "pylsp.plugins.jedi_completion"
jedi_definition = "pylsp.plugins.definition"
jedi_hover = "pylsp.plugins.hover"
jedi_highlight = "pylsp.plugins.highlight"
jedi_references = "pylsp.plugins.references"
jedi_rename = "pylsp.plugins.jedi_rename"
jedi_signature_help = "pylsp.plugins.signature"
jedi_symbols = "pylsp.plugins.symbols"
mccabe = "pylsp.plugins.mccabe_lint"
preload = "pylsp.plugins.preload_imports"
pycodestyle = "pylsp.plugins.pycodestyle_lint"
pydocstyle = "pylsp.plugins.pydocstyle_lint"
pyflakes = "pylsp.plugins.pyflakes_lint"
pylint = "pylsp.plugins.pylint_lint"
rope_completion = "pylsp.plugins.rope_completion"
rope_rename = "pylsp.plugins.rope_rename"
rope_autoimport = "pylsp.plugins.rope_autoimport"
yapf = "pylsp.plugins.yapf_format"

[project.scripts]
pylsp = "pylsp.__main__:main"

[tool.setuptools]
license-files = ["LICENSE"]
include-package-data = false

[tool.setuptools.packages.find]
exclude = ["contrib", "docs", "test", "test.*", "test.plugins", "test.plugins.*"]
namespaces = false

[tool.setuptools_scm]
write_to = "pylsp/_version.py"
write_to_template = "__version__ = \"{version}\"\n"  # VERSION_INFO is populated in __main__

[tool.pytest.ini_options]
testpaths = ["test"]
addopts = "--cov-report html --cov-report term --junitxml=pytest.xml --cov pylsp --cov test"

[tool.coverage.run]
concurrency = ["multiprocessing", "thread"]

``` 
**After update of project name:**
```toml

# Copyright 2017-2020 Palantir Technologies, Inc.
# Copyright 2021- Python Language Server Contributors.
[build-system]
	build-backend = "setuptools.build_meta"
	requires = ["setuptools>=61.2.0", "setuptools_scm[toml]>=3.4.3"]

[project]
	requires-python = ">=3.7"
	name = "test"
	description = "Python Language Server for the Language Server Protocol"
	dynamic = ["version"]
	readme = "README.md"
	dependencies = ["jedi>=0.17.2,<0.19.0", "python-lsp-jsonrpc>=1.0.0", "pluggy>=1.0.0", "docstring-to-markdown", "ujson>=3.0.0", "setuptools>=39.0.0"]

	[project.entry-points]

		[project.entry-points.pylsp]
			jedi_rename = "pylsp.plugins.jedi_rename"
			autopep8 = "pylsp.plugins.autopep8_format"
			pyflakes = "pylsp.plugins.pyflakes_lint"
			yapf = "pylsp.plugins.yapf_format"
			folding = "pylsp.plugins.folding"
			jedi_highlight = "pylsp.plugins.highlight"
			pycodestyle = "pylsp.plugins.pycodestyle_lint"
			jedi_hover = "pylsp.plugins.hover"
			rope_completion = "pylsp.plugins.rope_completion"
			preload = "pylsp.plugins.preload_imports"
			flake8 = "pylsp.plugins.flake8_lint"
			jedi_symbols = "pylsp.plugins.symbols"
			mccabe = "pylsp.plugins.mccabe_lint"
			pylint = "pylsp.plugins.pylint_lint"
			jedi_references = "pylsp.plugins.references"
			jedi_completion = "pylsp.plugins.jedi_completion"
			jedi_signature_help = "pylsp.plugins.signature"
			rope_rename = "pylsp.plugins.rope_rename"
			pydocstyle = "pylsp.plugins.pydocstyle_lint"
			rope_autoimport = "pylsp.plugins.rope_autoimport"
			jedi_definition = "pylsp.plugins.definition"

	[project.license]
		text = "MIT"

	[project.urls]
		Homepage = "https://github.com/python-lsp/python-lsp-server"

	[project.optional-dependencies]
		all = ["autopep8>=1.6.0,<2.1.0", "flake8>=5.0.0,<7", "mccabe>=0.7.0,<0.8.0", "pycodestyle>=2.9.0,<2.11.0", "pydocstyle>=6.3.0,<6.4.0", "pyflakes>=2.5.0,<3.1.0", "pylint>=2.5.0,<3", "rope>1.2.0", "yapf>=0.33.0", "whatthepatch>=1.0.2,<2.0.0"]
		autopep8 = ["autopep8>=1.6.0,<2.1.0"]
		pyflakes = ["pyflakes>=2.5.0,<3.1.0"]
		test = ["pylint>=2.5.0,<3", "pytest", "pytest-cov", "coverage", "numpy", "pandas", "matplotlib", "pyqt5", "flaky"]
		mccabe = ["mccabe>=0.7.0,<0.8.0"]
		pylint = ["pylint>=2.5.0,<3"]
		yapf = ["yapf>=0.33.0", "whatthepatch>=1.0.2,<2.0.0"]
		rope = ["rope>1.2.0"]
		pycodestyle = ["pycodestyle>=2.9.0,<2.11.0"]
		pydocstyle = ["pydocstyle>=6.3.0,<6.4.0"]
		flake8 = ["flake8>=5.0.0,<7"]
		websockets = ["websockets>=10.3"]

	[project.scripts]
		pylsp = "pylsp.__main__:main"

	[[project.authors]]
		name = "Python Language Server Contributors"

[tool]

	[tool.coverage]

		[tool.coverage.run]
			concurrency = ["multiprocessing", "thread"]

	[tool.setuptools_scm]
		# VERSION_INFO is populated in __main__
		write_to_template = "__version__ = \"{version}\"\n"
		write_to = "pylsp/_version.py"

	[tool.pytest]

		[tool.pytest.ini_options]
			testpaths = ["test"]
			addopts = "--cov-report html --cov-report term --junitxml=pytest.xml --cov pylsp --cov test"

	[tool.setuptools]
		license-files = ["LICENSE"]
		include-package-data = false

		[tool.setuptools.packages]

			[tool.setuptools.packages.find]
				exclude = ["contrib", "docs", "test", "test.*", "test.plugins", "test.plugins.*"]
				namespaces = false


```
