### ISSUE TITLE
Why list is null

### ISSUE THREAD

**Issue by mani1232** [TheElectronWill/night-config#138]
![image](https://github.com/TheElectronWill/night-config/assets/70480001/45ded902-7506-419c-8908-f1e5f623c2a6)
This null: https://github.com/mani1232/CustomBot/blob/dev-full-refactor/src/main/java/ua/mani123/config/Objects/BotConfig.java#L17
But creating with default is fine, and after convert back to object set list to null: https://github.com/mani1232/CustomBot/blob/dev-full-refactor/src/main/java/ua/mani123/config/ConfigUtils.java#L17

**Comment by TheElectronWill** [comment]
Well, I don't know exactly why because I cannot debug all the project, but I can try to give you some tips.

Have you checked the content of the file?

**Comment by TheElectronWill** [comment]
it is generated only if it doesn't exist, maybe an older version of the file is still there?

**Comment by mani1232** [comment]
```toml

[[DiscordBot]]
	BotId = 0
	BotToken = "TOKEN_CHANGE_IT_1"

[[DiscordBot]]
	BotId = 1
	BotToken = "TOKEN_CHANGE_IT_2"

[[DiscordBot]]
	BotId = 2
	BotToken = "TOKEN_CHANGE_IT_3"


```

No, it latest
