### ISSUE TITLE
Prettier toml serialization?

### ISSUE THREAD

**Issue by themg95** [TheElectronWill/night-config#185]
I've noticed that in older versions toml is serialized like this:
```toml
[category]
option1 = true
option2 = false
```
but now it's serialized like this:
```toml
category = {option1 = true, option2=false}
```
Is there an option to switch to the older formatting?
