### ISSUE TITLE
Indentation issue when saving with TOML

### ISSUE THREAD

**Issue by Euphillya** [TheElectronWill/night-config#194]
I'm using the TOML format in my Skyblock plugin. However, there seems to be a formatting issue when saving the configuration. The structure is not preserved correctly — the saved file contains unexpected tabs and nested indentation, which doesn't follow standard TOML formatting.

**Expected Result:**
```toml
config-version = 4
verbose = false

[settings.global.cache]
update-timer-seconds = 30

[settings.island]
region-distance = 10
max-islands = 500_000
teleport-outside-island = false

[settings.island.delete]
prevent-deletion-if-has-members = true
chunk-perimeter-island = false

[settings.island.invitation]
teleport-when-accepting = false

[settings.spawn]
enable = true
world-name = "world"
block-x = 0.0
block-y = 0.0
block-z = 0.0
yaw = 0.0
pitch = 0.0

[debug]
permission = false
```

**Actual Result:**
```toml
config-version = 4
verbose = false

	[settings.spawn]
		block-x = 0.0
		block-y = 0.0
		block-z = 0.0
		enable = true
		pitch = 0.0
		world-name = "world"
		yaw = 0.0

	[settings.island]
		teleport-outside-island = false
		region-distance = 10
		max-islands = 500000

		[settings.island.invitation]
			teleport-when-accepting-invitation = true

		[settings.island.delete]
			prevent-deletion-if-has-members = true
			chunk-perimeter-island = true

		[settings.global.cache]
			update-timer-seconds = 30

[debug]
	permission = false
```

**Code Sample:**

```java
package fr.euphyllia.skyllia.configuration.manager;

import com.electronwill.nightconfig.core.file.CommentedFileConfig;
import fr.euphyllia.skyllia.managers.ConfigManager;
import org.bukkit.Bukkit;
import org.bukkit.Location;

public class GeneralConfigManager implements ConfigManager {
   ...
    public GeneralConfigManager(CommentedFileConfig config) {
        this.config = config;
        loadConfig();
    }

    @Override
    public void loadConfig() {
        changed = false;
        this.configVersion = getOrSetDefault("config-version", 4, Integer.class);
        this.verbose = getOrSetDefault("verbose", false, Boolean.class);

        this.updateCacheTimer = getOrSetDefault("settings.global.cache.update-timer-seconds", 30, Integer.class);

        this.regionDistance = getOrSetDefault("settings.island.region-distance", -1, Integer.class);
        this.maxIslands = getOrSetDefault("settings.island.max-islands", 500_000, Integer.class);
        this.teleportOutsideIsland = getOrSetDefault("settings.island.teleport-outside-island", false, Boolean.class);

        this.preventDeletionIfHasMembers = getOrSetDefault("settings.island.delete.prevent-deletion-if-has-members", true, Boolean.class);
        this.deleteChunkPerimeterIsland = getOrSetDefault("settings.island.delete.chunk-perimeter-island", false, Boolean.class);

        this.teleportWhenAcceptingInvitation = getOrSetDefault("settings.island.invitation.teleport-when-accepting-invitation", true, Boolean.class);

        this.spawnEnabled = getOrSetDefault("settings.spawn.enable", true, Boolean.class);
        this.spawnWorld = getOrSetDefault("settings.spawn.world-name", "world", String.class);
        this.spawnX = getOrSetDefault("settings.spawn.block-x", 0.0, Double.class);
        this.spawnY = getOrSetDefault("settings.spawn.block-y", 64.0, Double.class);
        this.spawnZ = getOrSetDefault("settings.spawn.block-z", 0.0, Double.class);
        this.spawnYaw = getOrSetDefault("settings.spawn.yaw", 0.0f, Float.class);
        this.spawnPitch = getOrSetDefault("settings.spawn.pitch", 0.0f, Float.class);

        this.debugPermission = getOrSetDefault("debug.permission", false, Boolean.class);

        if (changed) {
            config.save();
        }
    }

    @Override
    @SuppressWarnings("unchecked")
    public <T> T getOrSetDefault(String path, T defaultValue, Class<T> expectedClass) {
        Object value = config.get(path);
        if (value == null) {
            config.set(path, defaultValue);
            changed = true;
            return defaultValue;
        }

        if (expectedClass.isInstance(value)) {
            return (T) value;
        }

        // Cas spécial : Integer → Long
        if (expectedClass == Long.class && value instanceof Integer) {
            return (T) Long.valueOf((Integer) value);
        }

        // Cas spécial : Double → Float
        if (expectedClass == Float.class && value instanceof Double) {
            return (T) Float.valueOf(((Double) value).floatValue());
        }

        throw new IllegalStateException("Cannot convert value at path '" + path + "' from " + value.getClass().getSimpleName() + " to " + expectedClass.getSimpleName());
    }
...
}

```
