### ISSUE TITLE
TOML - Comments on table arrays overwritten

### ISSUE THREAD

**Issue by t-boom** [TheElectronWill/Night-Config#28]
One more (less important) bug with comments in TOML

If you add comments to table arrays, only the last one is kept. Here's an example to better explain
```toml
[[products]] # Table List 1
name = "Hammer" # Name 1
sku = 738594937

[[products]] # Table List 2
name = "Nail" # Name 2
sku = 284758393
color = "gray"
```
becomes
```toml
# Table List 2
[[products]]
	# Name 1
	name = "Hammer"
	sku = 738594937

[[products]]
	color = "gray"
	# Name 2
	name = "Nail"
	sku = 284758393
```
Notice the first table in the array is now marked as `Table List 2` and the second is not marked.
