### ISSUE TITLE
TomlWriter append too many empty lines with tables.

### ISSUE THREAD

**Issue by LambdAurora** [TheElectronWill/night-config#83]
When only manipulating TOML tables, upon write, some empty lines get created at the start and the end of the file without being needed.

In the case of a TOML file with only a table and no key outside this table, an empty line will be appended at the start of the file.
The same case can be seen at the end of the file, two empty lines are appended, one should be enough.

**Reproduction**

Load a TOML file:
```toml
[table]
    # Comment
    key = "value"
```

then save it, you should see:
```toml
 < empty line >
[table]
    # Comment
    key = "value"
 < empty line >
```
